import {
  changeTrackedColumns,
  qualifiedTableName,
  type ColumnMapping,
  type DimensionalConfig,
  type Mapping,
  type ObjectGraph,
  type Table,
} from "@strata/metamodel";

/**
 * Dataform SQLX generation.
 *
 * **Why this is the feature the tool was missing.** `mapping.ts` has always modelled load
 * strategies, change-detection columns, four surrogate-key strategies, conformed
 * dimensions and point-in-time dimension lookups in full detail, and emitted nothing at
 * all. The README said "those mappings are what will generate the Dataform SQLX" and the
 * generator did not exist, so every warehouse using this tool still hand-wrote the SQL the
 * model already described.
 *
 * That gap matters most exactly where it hurts: SCD2. Hand-writing a slowly-changing
 * dimension merge is where data teams reliably lose weeks, and the bugs, a row that never
 * closes, two current versions of the same customer, a surrogate key that changes on every
 * run, are subtle, expensive and usually found in a report rather than in a test.
 *
 * **The shape of what comes out.** One `.sqlx` per mapping, plus a declaration per source
 * table nobody in this model produces, plus assertion files for the rules the model states
 * but Dataform's inline `assertions:` block cannot express. Everything is a pure function
 * of the model: run it twice on an unchanged model and the bytes are identical, which is
 * what makes it safe to run in CI and trivial to review.
 *
 * **What it deliberately does not do.** It never edits a hand-written file. `customSql` is
 * honoured verbatim when present, because a team that needs SQL this form cannot express
 * should stay in the tool with an escape hatch rather than abandon generation entirely.
 */

export interface DataformFile {
  /** Path relative to the Dataform repo root. */
  path: string;
  contents: string;
  /** The object this file was generated from. */
  objectId: string;
  kind: "declaration" | "model" | "assertion";
}

export interface DataformOptions {
  /** Path templates, matching `DataformConnection.paths`. */
  paths?: {
    declaration?: string;
    model?: string;
    assertion?: string;
  };
  /** Default project, when the model's target does not name one. */
  project?: string;
  /** Default dataset, when neither the table nor the model names one. */
  dataset?: string;
  /** Prepend a "generated, do not edit" header. Default true. */
  header?: boolean;
  /** Tags applied to every generated action, for `dataform run --tags`. */
  tags?: string[];
}

const DEFAULT_PATHS = {
  declaration: "definitions/sources/{dataset}/{name}.sqlx",
  model: "definitions/{layer}/{name}.sqlx",
  assertion: "definitions/assertions/{name}.sqlx",
};

// ---------------------------------------------------------------- helpers

/**
 * Backtick-quote a fully qualified name.
 *
 * Not optional: GCP project ids almost always contain hyphens, and BigQuery parses an
 * unquoted `acme-analytics-prod.dataset.table` as arithmetic. Getting this wrong produces
 * SQL that looks correct and fails against every real project.
 */
function quoted(name: string): string {
  return `\`${name}\``;
}

/**
 * The target table, as Dataform refers to it.
 *
 * **Never wrap this in backticks.** `self()` already expands to a fully qualified
 * *backticked* name, so quoting it again yields ``\`\`project.dataset.table\`\```, which
 * BigQuery rejects outright. Naming it once here is what stops the two spellings drifting
 * apart, and they already had: the incremental predicate used the bare form while every
 * SCD2 statement quoted it, so half the generated SQL was invalid.
 */
const SELF = "${self()}";

/** A bare identifier, quoted only when it is not a plain word. */
function ident(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : `\`${name}\``;
}

/**
 * Render a path template.
 *
 * `{layer}` collapses rather than producing an `_unknown` directory, matching how the
 * model layout engine treats a variable that resolves to nothing, a table with no layer
 * should land in `definitions/`, not `definitions/undefined/`.
 */
function renderPath(
  template: string,
  vars: { dataset?: string; name: string; layer?: string },
): string {
  return template
    .replace(/\{dataset\}/g, vars.dataset ?? "")
    .replace(/\{name\}/g, vars.name)
    .replace(/\{layer\}/g, vars.layer ?? "")
    .replace(/\/{2,}/g, "/")
    .replace(/^\//, "");
}

function header(objectName: string, kind: string): string {
  return [
    `-- Generated by strata from the ${kind} \`${objectName}\`.`,
    "-- Edits here are overwritten on the next generate; change the model instead.",
    "",
  ].join("\n");
}

/** JS object literal for a Dataform `config` block. Not JSON, keys are unquoted. */
function configBlock(entries: Record<string, unknown>): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(entries)) {
    if (value === undefined) continue;
    if (Array.isArray(value) && value.length === 0) continue;
    lines.push(`  ${key}: ${literal(value)}`);
  }
  return `config {\n${lines.join(",\n")}\n}\n`;
}

function literal(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `[${value.map(literal).join(", ")}]`;
  if (value && typeof value === "object") {
    const inner = Object.entries(value)
      .filter(([, v]) => v !== undefined && !(Array.isArray(v) && v.length === 0))
      .map(([k, v]) => `${k}: ${literal(v)}`);
    return `{ ${inner.join(", ")} }`;
  }
  return "null";
}

// ---------------------------------------------------------------- expressions

/**
 * The SQL producing one target column.
 *
 * An explicit expression wins. Otherwise a single source is a straight passthrough, and
 * anything else is `NULL`, which is deliberate: a column with several sources and no
 * expression is an incomplete mapping, and emitting the first source silently would hide
 * that. `NULL` plus the validator's `mapping/missingColumn` warning is the honest pair.
 */
function columnExpression(cm: ColumnMapping): string {
  if (cm.expression) return cm.expression;
  if (cm.sources.length === 1) return cm.sources[0]!;
  return "NULL";
}

/**
 * The surrogate key expression.
 *
 * `hash` uses `FARM_FINGERPRINT` over the business key, which is deterministic: the same
 * business key produces the same surrogate in dev, in prod and after a full rebuild. That
 * reproducibility is the whole reason to prefer it over a generated id, a warehouse whose
 * surrogate keys change on rebuild cannot be compared against yesterday's copy of itself.
 *
 * `CAST(... AS STRING)` on every part because the business key may be numeric, and
 * `CONCAT` on a mix of types is an error. The `|` separator stops `('a','bc')` and
 * `('ab','c')` hashing alike.
 *
 * For SCD2 the key must identify a *version*, not a business entity, so the validity start
 * joins the hash, otherwise every historical row for one customer shares a surrogate key
 * and the fact table cannot tell them apart.
 */
function surrogateKeyExpression(
  dim: DimensionalConfig,
  businessKeyExpressions: string[],
  options: { versioned: boolean; validFrom?: string },
): string {
  switch (dim.surrogateKeyStrategy) {
    case "uuid":
      return "GENERATE_UUID()";
    case "rowNumber":
      return `ROW_NUMBER() OVER (ORDER BY ${businessKeyExpressions.join(", ")})`;
    case "sourceProvided":
      // The mapping supplies it like any other column; nothing to synthesise.
      return "";
    case "hash":
    default: {
      const parts = [...businessKeyExpressions];
      if (options.versioned && options.validFrom) parts.push(options.validFrom);
      const casted = parts.map((part) => `CAST(${part} AS STRING)`);
      return `FARM_FINGERPRINT(CONCAT(${casted.join(", '|', ")}))`;
    }
  }
}

/** The FROM/JOIN chain for a mapping's sources. */
function fromClause(mapping: Mapping, graph: ObjectGraph, defaults: Defaults): string[] {
  const lines: string[] = [];

  mapping.sources.forEach((source, index) => {
    const table = resolveTable(graph, mapping, source.ref);
    const name = table ? quoted(qualifiedTableName(table, defaults)) : quoted(source.ref);
    const alias = ident(source.alias);

    if (index === 0) {
      lines.push(`FROM ${name} AS ${alias}`);
      return;
    }

    const join = source.join;
    if (!join) {
      // No join condition on a second source is a cross join whether or not anyone
      // intended it. Say so in the SQL rather than emitting a comma join that reads
      // like an oversight.
      lines.push(`CROSS JOIN ${name} AS ${alias}`);
      return;
    }
    lines.push(`${join.type.toUpperCase()} JOIN ${name} AS ${alias} ON ${join.on}`);
  });

  return lines;
}

/**
 * Dimension lookups, which turn a fact's natural keys into surrogate keys.
 *
 * `pointInTime` is the difference between a fact that reports today's customer segment and
 * one that reports the segment as it was when the order was placed. The first is a common
 * and quietly wrong answer, and it is only avoidable if the dimension keeps history, so
 * this joins on the row whose validity window contains the fact's own timestamp rather
 * than on the current row.
 */
function dimensionJoins(
  mapping: Mapping,
  graph: ObjectGraph,
  defaults: Defaults,
): { joins: string[]; columns: string[] } {
  const dim = mapping.dimensional;
  const joins: string[] = [];
  const columns: string[] = [];
  if (!dim || dim.dimensionLookups.length === 0) return { joins, columns };

  const eventTime = dim.watermarkColumn;
  const primary = mapping.sources[0]?.alias ?? "s";

  for (const lookup of dim.dimensionLookups) {
    const table = resolveTable(graph, mapping, lookup.dimension);
    const name = table ? quoted(qualifiedTableName(table, defaults)) : quoted(lookup.dimension);
    const alias = `dim_${lookup.column}`;

    /**
     * The dimension's business key, surrogate and validity columns.
     *
     * The mapping that *builds* the dimension is authoritative, because that is where the
     * names are declared. But it is frequently not in scope, a conformed dimension is
     * shared across marts and is very often built by a different model than the one
     * loading this fact, so falling back to the dimension table's own columns is not a
     * nicety.
     *
     * **Getting this wrong is a silent fan-out.** Join a fact to a type-2 dimension
     * without a validity predicate and you get one row per historical version of every
     * customer, quietly multiplying every measure in the table. It does not error, it does
     * not look wrong on the diagram, and it is found in a report months later.
     */
    const source = mappingFor(graph, mapping.model, lookup.dimension);
    const dimensionColumns = new Set(table?.columns.map((column) => column.name) ?? []);
    const pick = (declared: string | undefined, ...candidates: string[]): string | undefined =>
      declared ?? candidates.find((candidate) => dimensionColumns.has(candidate));

    const businessKey = source?.dimensional?.businessKey?.[0] ?? lookup.sourceColumn;
    const surrogate = source?.dimensional?.surrogateKey ?? lookup.column;
    const validFrom = pick(source?.dimensional?.validFromColumn, "valid_from", "effective_from");
    const validTo = pick(source?.dimensional?.validToColumn, "valid_to", "effective_to");
    const currentFlag = pick(source?.dimensional?.currentFlagColumn, "is_current", "current_flag");

    const conditions = [`${alias}.${ident(businessKey)} = ${primary}.${ident(lookup.sourceColumn)}`];

    if (lookup.pointInTime && validFrom && eventTime) {
      conditions.push(`${alias}.${ident(validFrom)} <= ${primary}.${ident(eventTime)}`);
      if (validTo) {
        conditions.push(
          `(${alias}.${ident(validTo)} IS NULL OR ${alias}.${ident(validTo)} > ${primary}.${ident(eventTime)})`,
        );
      }
    } else if (currentFlag) {
      conditions.push(`${alias}.${ident(currentFlag)} = TRUE`);
    }

    /**
     * A point-in-time lookup that could not find validity columns.
     *
     * Say so in the SQL rather than emitting a join that looks fine and fans out. A
     * comment a reviewer sees is a far better outcome than a measure that is silently
     * double-counted, and it names the two ways to fix it.
     */
    if (lookup.pointInTime && !(validFrom && eventTime)) {
      joins.push(
        `-- WARNING: point-in-time lookup requested for \`${lookup.column}\`, but ${
          !eventTime
            ? "the mapping declares no watermarkColumn to use as the event time"
            : `no validity columns were found on \`${name}\``
        }.`,
        "--          Joining without one returns a row per historical version. Declare the",
        "--          dimension's validFromColumn/validToColumn, or set pointInTime: false.",
      );
    }

    joins.push(`LEFT JOIN ${name} AS ${alias}`);
    joins.push(`  ON ${conditions.join("\n  AND ")}`);

    /**
     * `COALESCE` onto the unknown-member key.
     *
     * A fact row whose dimension lookup misses must not vanish and must not carry NULL, * both silently drop it from any inner-joined report. Routing it to a designated
     * unknown member keeps the row countable and makes the miss visible.
     */
    const reference = `${alias}.${ident(surrogate)}`;
    columns.push(
      lookup.unknownMemberKey === undefined
        ? `${reference} AS ${ident(lookup.column)}`
        : `COALESCE(${reference}, ${typeof lookup.unknownMemberKey === "string" ? `'${lookup.unknownMemberKey}'` : lookup.unknownMemberKey}) AS ${ident(lookup.column)}`,
    );
  }

  return { joins, columns };
}

interface Defaults {
  project?: string;
  dataset?: string;
}

function resolveTable(graph: ObjectGraph, mapping: Mapping, ref: string): Table | undefined {
  const resolved = graph.resolve(ref, { model: mapping.model, kind: "table" })?.target.object;
  return resolved?.kind === "table" ? (resolved as Table) : undefined;
}

/**
 * The mapping that produces a given table, if this model builds it.
 *
 * `modelName` is optional because `model` is optional on every object: a mapping that
 * names no model cannot be searched within one, and returning undefined lets the caller
 * fall back to the lookup's own column names rather than crash on a degenerate model.
 */
function mappingFor(
  graph: ObjectGraph,
  modelName: string | undefined,
  targetRef: string,
): Mapping | undefined {
  if (!modelName) return undefined;
  const target = graph.resolve(targetRef, { model: modelName, kind: "table" })?.target.object;
  if (!target) return undefined;

  for (const entry of graph.inModel(modelName)) {
    if (entry.object.kind !== "mapping") continue;
    const candidate = entry.object as Mapping;
    const produced = graph.resolve(candidate.target, { model: modelName, kind: "table" })?.target.object;
    if (produced?.id === target.id) return candidate;
  }
  return undefined;
}

// ---------------------------------------------------------------- select

/** The SELECT every strategy is built from. */
function selectStatement(
  mapping: Mapping,
  graph: ObjectGraph,
  defaults: Defaults,
  extra: { columns?: string[]; where?: string[] } = {},
): string {
  const dim = mapping.dimensional;
  const lookupColumns = new Set(dim?.dimensionLookups.map((l) => l.column) ?? []);

  const columns = mapping.columnMappings
    // A column resolved by a dimension lookup is produced by the join, not by the mapping.
    .filter((cm) => !lookupColumns.has(cm.target))
    .map((cm) => `${columnExpression(cm)} AS ${ident(cm.target)}`);

  const { joins, columns: lookupSelects } = dimensionJoins(mapping, graph, defaults);
  const all = [...columns, ...lookupSelects, ...(extra.columns ?? [])];

  const lines: string[] = [];
  lines.push("SELECT");
  lines.push(all.map((column) => `  ${column}`).join(",\n"));
  lines.push(...fromClause(mapping, graph, defaults));
  lines.push(...joins);

  const where = [
    ...mapping.sources.map((source) => source.filter).filter((f): f is string => Boolean(f)),
    ...(mapping.where ? [mapping.where] : []),
    ...(extra.where ?? []),
  ];
  if (where.length > 0) lines.push(`WHERE ${where.join("\n  AND ")}`);

  if (mapping.groupBy.length > 0) lines.push(`GROUP BY ${mapping.groupBy.join(", ")}`);
  if (mapping.having) lines.push(`HAVING ${mapping.having}`);

  return lines.join("\n");
}

/** Business key expressions in *source* terms, for hashing before aliases exist. */
function businessKeyExpressions(mapping: Mapping, dim: DimensionalConfig): string[] {
  return dim.businessKey.map((key) => {
    const cm = mapping.columnMappings.find((entry) => entry.target === key);
    return cm ? columnExpression(cm) : key;
  });
}

/**
 * The incremental predicate.
 *
 * Compares against the target's own high-water mark rather than a fixed date, so a
 * pipeline that has not run for a week catches up on its own. `lookbackDays` re-processes
 * a trailing window because source rows arrive late, and a strict `>` would skip anything
 * that landed after the previous run read the table.
 */
function incrementalWhere(mapping: Mapping, dim: DimensionalConfig | undefined): string | undefined {
  const watermark = dim?.watermarkColumn;
  if (!watermark) return undefined;

  const alias = mapping.sources[0]?.alias ?? "s";
  const lookback = dim?.lookbackDays ?? 0;
  const floor =
    lookback > 0
      ? `DATE_SUB(MAX(${ident(watermark)}), INTERVAL ${lookback} DAY)`
      : `MAX(${ident(watermark)})`;

  return `${alias}.${ident(watermark)} >= (SELECT ${floor} FROM ${SELF})`;
}

// ---------------------------------------------------------------- strategies

/**
 * Slowly-changing dimension, type 2, the reason this generator exists.
 *
 * Emitted as `type: "operations"` because the correct load is **two statements** and no
 * single BigQuery `MERGE` can do it: a merge applies at most one action per matched row,
 * and a changed business key needs both its current row closed *and* a new row opened.
 * Attempting it as one statement is the single most common way hand-written SCD2 goes
 * wrong, it silently keeps the old values or leaves two rows flagged current.
 *
 * So: close first, then insert. The insert's `LEFT JOIN ... WHERE IS NULL` picks up both
 * genuinely new keys and the keys the merge just closed, which is why the order matters
 * and why they cannot be swapped.
 */
function scd2Statements(
  mapping: Mapping,
  graph: ObjectGraph,
  defaults: Defaults,
  dim: DimensionalConfig,
): string[] {
  const validFrom = dim.validFromColumn ?? "valid_from";
  const validTo = dim.validToColumn ?? "valid_to";
  const currentFlag = dim.currentFlagColumn ?? "is_current";
  const hashColumn = dim.hashColumn ?? "change_hash";

  const tracked = changeTrackedColumns(mapping);
  const trackedExpressions = tracked.map((name) => {
    const cm = mapping.columnMappings.find((entry) => entry.target === name);
    return `CAST(${cm ? columnExpression(cm) : name} AS STRING)`;
  });
  const hashExpression =
    trackedExpressions.length > 0
      ? `FARM_FINGERPRINT(CONCAT(${trackedExpressions.join(", '|', ")}))`
      : "0";

  const businessKeys = businessKeyExpressions(mapping, dim);
  const surrogate = dim.surrogateKey;
  const surrogateExpression = surrogate
    ? surrogateKeyExpression(dim, businessKeys, { versioned: true, validFrom: "CURRENT_TIMESTAMP()" })
    : "";

  // The staged source: every mapped column plus the audit columns the strategy owns.
  const audit = [
    `${hashExpression} AS ${ident(hashColumn)}`,
    ...(surrogate && surrogateExpression ? [`${surrogateExpression} AS ${ident(surrogate)}`] : []),
  ];
  const staged = selectStatement(mapping, graph, defaults, { columns: audit });

  const keyJoin = dim.businessKey
    .map((key) => `target.${ident(key)} = source.${ident(key)}`)
    .join("\n    AND ");

  const inserted = [
    ...mapping.columnMappings.map((cm) => cm.target),
    ...(surrogate ? [surrogate] : []),
    hashColumn,
    validFrom,
    validTo,
    currentFlag,
  ];

  const expire = [
    "-- 1. Close the current row of every business key whose tracked columns changed.",
    "--    Runs first so the insert below can find those keys as \"no current row\".",
    `MERGE ${SELF} AS target`,
    "USING (",
    indent(staged, "  "),
    ") AS source",
    `ON ${keyJoin}`,
    `    AND target.${ident(currentFlag)} = TRUE`,
    `WHEN MATCHED AND target.${ident(hashColumn)} != source.${ident(hashColumn)} THEN UPDATE SET`,
    `  ${ident(validTo)} = CURRENT_TIMESTAMP(),`,
    `  ${ident(currentFlag)} = FALSE`,
  ].join("\n");

  const insert = [
    "-- 2. Open a new version for every key with no current row: brand new keys, and the",
    "--    keys step 1 just closed.",
    `INSERT INTO ${SELF} (${inserted.map(ident).join(", ")})`,
    "SELECT",
    `  ${[...mapping.columnMappings.map((cm) => `source.${ident(cm.target)}`), ...(surrogate ? [`source.${ident(surrogate)}`] : []), `source.${ident(hashColumn)}`].join(",\n  ")},`,
    `  CURRENT_TIMESTAMP() AS ${ident(validFrom)},`,
    `  CAST(NULL AS TIMESTAMP) AS ${ident(validTo)},`,
    `  TRUE AS ${ident(currentFlag)}`,
    "FROM (",
    indent(staged, "  "),
    ") AS source",
    `LEFT JOIN ${SELF} AS target`,
    `  ON ${keyJoin}`,
    `  AND target.${ident(currentFlag)} = TRUE`,
    `WHERE target.${ident(dim.businessKey[0] ?? "id")} IS NULL`,
  ].join("\n");

  return [expire, insert];
}

function indent(text: string, prefix: string): string {
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? prefix + line : line))
    .join("\n");
}

// ---------------------------------------------------------------- files

/** One `.sqlx` for one mapping. */
export function generateMappingSqlx(
  graph: ObjectGraph,
  mapping: Mapping,
  options: DataformOptions = {},
): DataformFile {
  const model = mapping.model ? graph.modelNamed(mapping.model) : undefined;
  const defaults: Defaults = {
    project: options.project ?? model?.target?.project,
    dataset: options.dataset ?? model?.target?.dataset,
  };

  const target = resolveTable(graph, mapping, mapping.target);
  const dim = mapping.dimensional;
  const name = target?.name ?? mapping.target;
  const schema = target?.dataset ?? defaults.dataset;
  const layer = target?.layer;

  const tags = [...(options.tags ?? []), ...(mapping.stage ? [slug(mapping.stage)] : [])];

  /**
   * Assertions Dataform can run inline.
   *
   * The uniqueness of a dimension's business key is only true *among current rows* once
   * history is kept, and the inline form cannot express that qualifier, so it is claimed
   * only where it actually holds, and the SCD2 case gets a real assertion file instead.
   */
  const uniqueKey = dim?.surrogateKey
    ? [dim.surrogateKey]
    : target?.primaryKey?.length
      ? target.primaryKey
      : undefined;

  const nonNull = target?.columns
    .filter((column) => column.mode === "REQUIRED")
    .map((column) => column.name);

  const body: string[] = [];
  let type: string;
  const config: Record<string, unknown> = {};

  if (mapping.loadStrategy === "declaration") {
    // A declaration has no body at all: it tells Dataform a table exists and is produced
    // elsewhere, which is what makes it referenceable without claiming to build it.
    return {
      path: renderPath(options.paths?.declaration ?? DEFAULT_PATHS.declaration, {
        ...(schema ? { dataset: schema } : {}),
        name,
      }),
      contents:
        (options.header === false ? "" : header(mapping.name, "mapping")) +
        configBlock({ type: "declaration", schema, name }),
      objectId: mapping.id,
      kind: "declaration",
    };
  }

  switch (mapping.loadStrategy) {
    /**
     * SCD2 is operations, not a table or an incremental: the load is two statements and
     * `hasOutput` is what lets the rest of the project still reference it as a table.
     */
    case "scd2": {
      type = "operations";
      config.hasOutput = true;
      body.push(...scd2Statements(mapping, graph, defaults, dim!));
      break;
    }

    /**
     * SCD1 overwrites in place and keeps no history, so it is a straight upsert keyed on
     * the business key, the surrogate key is derived from that key and therefore stable
     * across runs, which is what makes the upsert idempotent.
     */
    case "scd1": {
      type = "incremental";
      config.uniqueKey = dim?.businessKey.length ? dim.businessKey : uniqueKey;
      body.push(withSurrogate(mapping, graph, defaults, dim, false));
      break;
    }

    case "merge": {
      type = "incremental";
      config.uniqueKey = dim?.businessKey.length ? dim.businessKey : uniqueKey;
      body.push(withSurrogate(mapping, graph, defaults, dim, false));
      break;
    }

    case "incremental": {
      type = "incremental";
      if (dim?.surrogateKey) config.uniqueKey = [dim.surrogateKey];
      else if (dim?.businessKey.length) config.uniqueKey = dim.businessKey;
      body.push(withSurrogate(mapping, graph, defaults, dim, true));
      break;
    }

    /**
     * A dated full copy, one per run.
     *
     * Keyed on the snapshot date *plus* the business key so a re-run on the same day
     * replaces that day's copy rather than doubling it, which is the difference between
     * a table you can safely retry and one where a failed run leaves you counting
     * everything twice. Partitioned on the date because every read filters on it.
     */
    case "snapshot": {
      type = "incremental";
      const dateColumn = dim?.snapshotDateColumn ?? "snapshot_date";
      config.uniqueKey = [dateColumn, ...(dim?.businessKey ?? [])];
      body.push(
        selectStatement(mapping, graph, defaults, {
          columns: [`CURRENT_DATE() AS ${ident(dateColumn)}`],
        }),
      );
      // The declared partitioning wins if the table names one; otherwise the snapshot
      // date is the only sensible choice and leaving it unpartitioned is a cost bug.
      if (!target?.partitioning) config.bigquery = { partitionBy: dateColumn };
      break;
    }

    /** Append keeps every row, so it must not carry a uniqueKey, that would upsert. */
    case "append": {
      type = "incremental";
      body.push(withSurrogate(mapping, graph, defaults, dim, true));
      break;
    }

    case "full":
    default: {
      type = "table";
      body.push(withSurrogate(mapping, graph, defaults, dim, false));
      break;
    }
  }

  if (target?.partitioning || target?.clustering?.length) {
    config.bigquery = {
      ...(config.bigquery as Record<string, unknown> | undefined),
      ...(target.partitioning && "field" in target.partitioning && target.partitioning.field
        ? { partitionBy: target.partitioning.field }
        : {}),
      ...(target.clustering?.length ? { clusterBy: target.clustering } : {}),
    };
  }

  // Inline assertions are skipped for SCD2: uniqueness there holds only among current
  // rows, and a bare uniqueKey assertion would fail the moment history exists.
  if (mapping.loadStrategy !== "scd2") {
    const assertions: Record<string, unknown> = {};
    if (uniqueKey?.length) assertions.uniqueKey = uniqueKey;
    if (nonNull?.length) assertions.nonNull = nonNull;
    if (Object.keys(assertions).length > 0) config.assertions = assertions;
  }

  const contents =
    (options.header === false ? "" : header(mapping.name, "mapping")) +
    configBlock({
      type,
      schema,
      name,
      ...(mapping.description ? { description: mapping.description } : {}),
      ...config,
      ...(tags.length > 0 ? { tags } : {}),
    }) +
    "\n" +
    (mapping.customSql ? mapping.customSql.trimEnd() : body.join("\n\n---\n\n")) +
    "\n";

  return {
    path: renderPath(options.paths?.model ?? DEFAULT_PATHS.model, {
      ...(schema ? { dataset: schema } : {}),
      name,
      ...(layer ? { layer } : {}),
    }),
    contents,
    objectId: mapping.id,
    kind: "model",
  };
}

/** The SELECT plus a synthesised surrogate key and, when incremental, the watermark filter. */
function withSurrogate(
  mapping: Mapping,
  graph: ObjectGraph,
  defaults: Defaults,
  dim: DimensionalConfig | undefined,
  incremental: boolean,
): string {
  const extraColumns: string[] = [];

  if (dim?.surrogateKey && dim.surrogateKeyStrategy !== "sourceProvided") {
    const expression = surrogateKeyExpression(dim, businessKeyExpressions(mapping, dim), {
      versioned: false,
    });
    if (expression) extraColumns.push(`${expression} AS ${ident(dim.surrogateKey)}`);
  }

  const select = selectStatement(mapping, graph, defaults, { columns: extraColumns });

  const predicate = incremental ? incrementalWhere(mapping, dim) : undefined;
  if (!predicate) return select;

  /**
   * `when(incremental(), ...)` rather than a plain WHERE.
   *
   * On a first run, or after a full refresh, the target does not exist and
   * `SELECT MAX(...) FROM ${self()}` would fail. Dataform only emits this branch on an
   * incremental run, which is exactly when the table is guaranteed to be there.
   */
  return `${select}\n\${when(incremental(), \`  ${select.includes("WHERE") ? "AND" : "WHERE"} ${predicate}\`)}`;
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

/**
 * Declarations for tables this model reads but does not build.
 *
 * Without them Dataform has no node for the source and cannot order the graph, so the
 * pipeline either fails to compile or silently runs before its input is ready.
 */
export function generateDeclarations(
  graph: ObjectGraph,
  modelName: string,
  options: DataformOptions = {},
): DataformFile[] {
  const model = graph.modelNamed(modelName);
  const defaults: Defaults = {
    project: options.project ?? model?.target?.project,
    dataset: options.dataset ?? model?.target?.dataset,
  };

  const mappings = graph
    .inModel(modelName)
    .filter((entry) => entry.object.kind === "mapping")
    .map((entry) => entry.object as Mapping);

  const produced = new Set<string>();
  for (const mapping of mappings) {
    const target = graph.resolve(mapping.target, { model: modelName, kind: "table" })?.target.object;
    if (target) produced.add(target.id);
  }

  const files: DataformFile[] = [];
  const seen = new Set<string>();

  for (const mapping of mappings) {
    for (const source of mapping.sources) {
      const table = resolveTable(graph, mapping, source.ref);
      if (!table || produced.has(table.id) || seen.has(table.id)) continue;
      seen.add(table.id);

      const schema = table.dataset ?? defaults.dataset;
      files.push({
        path: renderPath(options.paths?.declaration ?? DEFAULT_PATHS.declaration, {
          ...(schema ? { dataset: schema } : {}),
          name: table.name,
        }),
        contents:
          (options.header === false ? "" : header(table.name, "table")) +
          configBlock({ type: "declaration", schema, name: table.name }),
        objectId: table.id,
        kind: "declaration",
      });
    }
  }

  return files;
}

/**
 * Assertion files for rules the inline `assertions:` block cannot express.
 *
 * Two kinds, both of which are real governance rules the model already states:
 *
 *  - **Referential integrity.** BigQuery does not enforce foreign keys, so a modelled
 *    relationship is a claim nobody checks unless something checks it. This is that.
 *  - **SCD2 single-current.** "One current row per business key" is the invariant that
 *    makes a type-2 dimension usable, and it is exactly what a botched merge breaks.
 */
export function generateAssertions(
  graph: ObjectGraph,
  modelName: string,
  options: DataformOptions = {},
): DataformFile[] {
  const model = graph.modelNamed(modelName);
  const defaults: Defaults = {
    project: options.project ?? model?.target?.project,
    dataset: options.dataset ?? model?.target?.dataset,
  };
  const template = options.paths?.assertion ?? DEFAULT_PATHS.assertion;
  const files: DataformFile[] = [];

  for (const entry of graph.inModel(modelName)) {
    if (entry.object.kind !== "table") continue;
    const table = entry.object as Table;

    for (const fk of table.foreignKeys) {
      if (!fk.assert) continue;
      const parent = graph.resolve(fk.references.table, { model: modelName, kind: "table" })?.target
        .object as Table | undefined;
      if (!parent) continue;

      const name = `assert_${fk.name}`;
      const joinOn = fk.columns
        .map((column, index) => `p.${ident(fk.references.columns[index] ?? column)} = c.${ident(column)}`)
        .join("\n  AND ");
      const notNull = fk.columns.map((column) => `c.${ident(column)} IS NOT NULL`).join(" AND ");

      files.push({
        path: renderPath(template, { name }),
        contents:
          (options.header === false ? "" : header(fk.name, "foreign key")) +
          configBlock({ type: "assertion", schema: defaults.dataset, name }) +
          "\n" +
          [
            "-- Every child row must find its parent. BigQuery does not enforce foreign",
            "-- keys, so without this the relationship is a claim nobody checks.",
            "SELECT c.*",
            `FROM ${quoted(qualifiedTableName(table, defaults))} AS c`,
            `LEFT JOIN ${quoted(qualifiedTableName(parent, defaults))} AS p`,
            `  ON ${joinOn}`,
            `WHERE ${notNull}`,
            `  AND p.${ident(fk.references.columns[0] ?? "id")} IS NULL`,
          ].join("\n") +
          "\n",
        objectId: table.id,
        kind: "assertion",
      });
    }
  }

  for (const entry of graph.inModel(modelName)) {
    if (entry.object.kind !== "mapping") continue;
    const mapping = entry.object as Mapping;
    if (mapping.loadStrategy !== "scd2") continue;

    const dim = mapping.dimensional;
    if (!dim || dim.businessKey.length === 0) continue;

    const target = resolveTable(graph, mapping, mapping.target);
    if (!target) continue;

    const currentFlag = dim.currentFlagColumn ?? "is_current";
    const name = `assert_${target.name}_single_current`;
    const keys = dim.businessKey.map(ident).join(", ");

    files.push({
      path: renderPath(template, { name }),
      contents:
        (options.header === false ? "" : header(mapping.name, "mapping")) +
        configBlock({ type: "assertion", schema: defaults.dataset, name }) +
        "\n" +
        [
          "-- A type-2 dimension must have exactly one current row per business key.",
          "-- Two is what a merge that closed nothing looks like; zero is what a merge",
          "-- that closed everything looks like. Both are silent without this.",
          `SELECT ${keys}, COUNT(*) AS current_rows`,
          `FROM ${quoted(qualifiedTableName(target, defaults))}`,
          `WHERE ${ident(currentFlag)} = TRUE`,
          `GROUP BY ${keys}`,
          "HAVING COUNT(*) > 1",
        ].join("\n") +
        "\n",
      objectId: mapping.id,
      kind: "assertion",
    });
  }

  return files;
}

/** Every Dataform file for one physical model. */
export function generateDataform(
  graph: ObjectGraph,
  modelName: string,
  options: DataformOptions = {},
): DataformFile[] {
  const model = graph.modelNamed(modelName);
  if (!model) throw new Error(`no model named \`${modelName}\``);
  if (model.tier !== "physical") {
    throw new Error(
      `\`${modelName}\` is a ${model.tier} model; Dataform is only generated from physical models`,
    );
  }

  const mappings = graph
    .inModel(modelName)
    .filter((entry) => entry.object.kind === "mapping")
    .map((entry) => entry.object as Mapping);

  return [
    ...generateDeclarations(graph, modelName, options),
    ...mappings.map((mapping) => generateMappingSqlx(graph, mapping, options)),
    ...generateAssertions(graph, modelName, options),
  ];
}
