apiVersion: v2
name: strata
description: Git-native data modelling for BigQuery, self-hosted in your own cluster
type: application
version: 1.0.1
appVersion: 1.0.1
keywords:
  - data-modelling
  - erd
  - bigquery
  - dataform
  - gitops
home: https://github.com/rk-chavali/strata
sources:
  - https://github.com/rk-chavali/strata
maintainers:
  - name: strata
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: 'false'
